# Generated by Django 5.1.6 on 2025-05-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0002_alter_artikel_options_alter_kategori_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artikel",
            name="slug",
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]