# Generated by Django 5.1.6 on 2025-05-06 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pengguna", "0002_biodata_foto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biodata",
            options={"verbose_name_plural": "1. Biodata"},
        ),
    ]